### ISSUE TITLE
Command 'tfsec.runTfsec' not found

### ISSUE THREAD

**Issue by JayBkr** [tfsec/vscode-tfsec#4]
Running tfsec v0.39.20 on Windows 10 via chocolatey in VSCode Version: 1.55.1 and when I try and use the extension, the Run tfsec now button does not do anything but pressing the "play" icon in the top right of the extension produces the error : "command 'tfsec.runTfsec' not found" 

I can run tfsec from my console without issue

**Comment by owenrumney** [comment]
Thanks @JayBkr i will take a look. I need to get a windows VM up and running but should be easy enough to resolve

**Comment by owenrumney** [comment]
@JayBkr  this should be resolved in v1.1.1 - please reopen if not fixed
