### ISSUE TITLE
Error Running 

### ISSUE THREAD

**Issue by jpmicrosoft** [tfsec/vscode-tfsec#6]
When running in VSCode via the button.

![image](https://user-images.githubusercontent.com/48604544/117070495-cfeb3880-acfb-11eb-98fa-524fd9d4b987.png)

Error: unknown flag: --force-all-dirs
Usage:
  tfsec [directory] [flags]

Flags:
  -e, --exclude string        Provide checks via , without space to exclude from run.
      --exclude-dir strings   Exclude a directory from the scan. You can use this flag multiple times to exclude further directories.
  -f, --format string         Select output format: default, json, csv, checkstyle, junit
  -h, --help                  help for tfsec
      --no-color              Disable colored output (American style!)
      --no-colour             Disable coloured output
  -s, --soft-fail             Runs checks but suppresses error code
      --tfvars-file string    Path to .tfvars file
  -v, --version               Show version information and exit

unknown flag: --force-all-dirs

**Comment by owenrumney** [comment]
Hey @jpmicrosoft, looks like your running a pretty old version of tfsec on your Path there. In the Vscode terminal where tfsec has failed could you run

tfsec.exe  - - version

And let me know what it is?

**Comment by owenrumney** [comment]
There is also a setting in the extension settings to turn of scanning all folders, would be interesting to know if that being false makes it run

**Comment by jpmicrosoft** [comment]
> Hey @jpmicrosoft, looks like your running a pretty old version of tfsec on your Path there. In the Vscode terminal where tfsec has failed could you run
> 
> `tfsec.exe --version`
> 
> And let me know what it is?

@owenrumney  You were correct, I forgot I installed via chocolatey last year and it was version 0.23.1. - Thanks for the help.

**Comment by jpmicrosoft** [comment]
> There is also a setting in the extension settings to turn of scanning all folders, would be interesting to know if that being false makes it run

I did not test this prior to removing it.

**Comment by jpmicrosoft** [comment]
Thanks for solving the issue.
